use_frameworks!

source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'LZDependencyControllerkit_Example' do
  pod 'LZDependencyControllerkit', :path => '../'

  pod 'LZDependencyToolkit', :path => '../../LZDependencyToolkit'
  
  target 'LZDependencyControllerkit_Tests' do
    inherit! :search_paths
  end
end
